Update HTML file using the workflow
gautamkrishnar/blog-post-workflow pull request #265
Opened 2024-08-03 04:46 UTC by muktoakash

* **Please check if the PR fulfills these requirements**
- [ x] The commit message follows our contribution guidelines
- [ x] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Updates the readme file with step-by-step description of how to use this repo to update index.html (or any other html file for that matter). Very useful for automatically updating webpages that are hosted through Github Pages.

* **What is the current behavior?** (You can also link to an open issue here)
Currently all updates happen to README.md of the user's repo. While this is nice, it is even nicer to have the option to automatically update and deploy webpages hosted on Github.

* **What is the new behavior (if this is a feature change)?**
N/A. This just updates the ReadMe file with new instructions.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
Repo needs to be forked and action.yml needs to be modified.

* **Other information**:
This is mostly an information update. I had to figure out how to do it myself, so thought others may also benefit from this information.

2024-08-16 23:24 UTC, gautamkrishnar commented
@muktoakash forking the repo is not required in this case. simply pass down the `readme_path` to the main blog post workflow itself. It should work just fine. 

Just use the following file:
```yaml
name: Latest blog post workflow
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:
permissions:
      contents: write

jobs:
  update-readme-with-youtube:
    name: Update this repo's index.html with latest blog titles from blogspot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          readme_path: 'index.html'
          feed_list: "http://blog_name.blogspot.com/feeds/posts/default?alt=rss"
          template: '<li><a href="$url">$title</a></li>$newline'
          committer_email: "your_email@example.com"
```

2024-08-16 23:29 UTC, gautamkrishnar requested changes

2024-08-16 23:29 UTC, gautamkrishnar commented on README.md
> +
This step is not required

2024-08-16 23:29 UTC, gautamkrishnar commented on README.md
> +```
Add an instruction to create index.html

2024-08-16 23:29 UTC, gautamkrishnar commented on README.md
> +            feed_list: "http://blog_name.blogspot.com/feeds/posts/default?alt=rss"
add `readme_path: 'index.html'`

2024-09-04 20:23 UTC, muktoakash reviewed
@gautamkrishnar Changes made as suggested.

2024-09-05 01:12 UTC, merged

2024-09-05 01:12 UTC, gautamkrishnar commented
Thanks for contributing. LGTM 👍🏻

2024-09-05 01:13 UTC, gautamkrishnar commented
@all-contributors please add @muktoakash for docs